---
title: "Gapminder Bubbles"
author: "Marc A.T. Teunis"
date: "12-9-2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(ggplot2)
library(gapminder)
library(gganimate)
library(gifski)
library(tidyverse)
library(png)

theme_set(theme_bw())


gapminder_animation <- ggplot(gapminder::gapminder, aes(gdpPercap, 
                                             lifeExp, 
                                             size = pop, 
                                             colour = continent)) +
  geom_point(alpha = 0.7, show.legend = TRUE) +
#  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
 # facet_wrap(~ continent) +

    # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) + ## regulation the actual layers for the animation
  ease_aes('linear')

gapminder_animation
## ------------------------------------------------------------------------
# library(av)
# p <- ggplot(airquality, 
#             aes(x = Day, 
#                 y = Temp)) + 
#   geom_line(size = 2, colour = 'steelblue') + 
#   transition_states(state = Month, 
#                     transition_length = 4, 
#                     state_length = 2) + 
#   shadow_mark(size = 0.3, colour = 'lightgrey')
# animate(p, renderer = av_renderer())
# 

```

